# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-15 02:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallToAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('action_item', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=25)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2017, 1, 15, 2, 9, 42, 190255, tzinfo=utc))),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Accepted Cta',
                'verbose_name_plural': 'Accepted Cta',
            },
        ),
        migrations.CreateModel(
            name='CtaUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('is_activity_public', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_organization', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2017, 1, 15, 2, 9, 42, 188003, tzinfo=utc))),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserCallToAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cta', models.CharField(max_length=200)),
                ('status', models.IntegerField(choices=[(0, 'REJECTED'), (1, 'ACCEPTED'), (2, 'BOOKMARKED')])),
                ('created_at', models.DateTimeField(default=datetime.datetime(2017, 1, 15, 2, 9, 42, 191779, tzinfo=utc))),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cta.CtaUser')),
            ],
            options={
                'verbose_name': 'User Call To Action',
                'verbose_name_plural': 'User Call To Actions',
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'ALLOW'), (0, 'BLOCK')])),
                ('created_at', models.DateTimeField(default=datetime.datetime(2017, 1, 15, 2, 9, 42, 193359, tzinfo=utc))),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_subscriber', to='cta.CtaUser')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_subscription', to='cta.CtaUser')),
            ],
            options={
                'verbose_name': 'User Subscription',
                'verbose_name_plural': 'User Subscriptions',
            },
        ),
        migrations.AddField(
            model_name='calltoaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cta.CtaUser'),
        ),
    ]
