# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-15 02:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cta', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calltoaction',
            options={'verbose_name': 'Call To Action', 'verbose_name_plural': 'Call To Actions'},
        ),
        migrations.RenameField(
            model_name='calltoaction',
            old_name='user',
            new_name='created_by',
        ),
        migrations.AlterField(
            model_name='calltoaction',
            name='action_item',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='calltoaction',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 15, 2, 39, 43, 371004, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ctauser',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 15, 2, 39, 43, 369015, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='usercalltoaction',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 15, 2, 39, 43, 372569, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 15, 2, 39, 43, 373958, tzinfo=utc)),
        ),
    ]
